stages:
  - build
  - deploy
  - test

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - docker info

build:
  stage: build
  script:
    - docker build -t $DOCKER_HUB_USERNAME/gym_website .
    - docker login -u $DOCKER_HUB_USERNAME -p $DOCKER_HUB_PASSWORD
    - docker push $DOCKER_HUB_USERNAME/gym_website

deploy:
  stage: deploy
  script:
    - echo "Deploy step"

test:
  stage: test
  script:
    - echo "Test step"
