image: docker:latest

services:
  - docker:dind

variables:
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: "fafa0ta/gym_website"  # یوزرنیم خودت رو جایگزین کن

stages:
  - build
  - deploy
  - test

build:
  stage: build
  script:
    - echo "Building Docker image..."
    - docker build -t $IMAGE_NAME .
    - docker login -u "$DOCKER_HUB_USERNAME" -p "$DOCKER_HUB_PASSWORD"
    - docker push $IMAGE_NAME

deploy:
  stage: deploy
  script:
    - echo "Deploying application..."
    # اینجا می‌تونی کامندهای مربوط به دیپلوی رو اضافه کنی

test:
  stage: test
  script:
    - echo "Running tests..."
    - docker run --rm $IMAGE_NAME echo "Container is running correctly!"
